field: 1bed2d77-ef7e-4669-9d78-1cc3a14d89a1
fieldLayouts:
  0eaf6e52-6e0a-46a9-a8a1-6f5eea7d5e6d:
    tabs:
      -
        fields:
          336ffeb1-53e6-4863-95eb-7b0eaa0d0166:
            required: false
            sortOrder: 6
          3456206b-0211-42fd-a68a-b07cef972f0c:
            required: false
            sortOrder: 3
          36709743-a130-4430-8afa-667b7ff9ddfe:
            required: false
            sortOrder: 4
          5b3d9079-ccd1-4561-bd6b-26ec0fafdb66:
            required: false
            sortOrder: 2
          8ccb8a7f-e524-4fa5-a22f-bf9728352fd3:
            required: false
            sortOrder: 1
          b9bccb2a-535c-4a57-b71e-e7a40f23c6d6:
            required: false
            sortOrder: 5
        name: Content
        sortOrder: 1
fields:
  336ffeb1-53e6-4863-95eb-7b0eaa0d0166:
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: ''
    name: Items
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - f8c5a70b-5505-437a-a22e-1e1f9d28f1e9
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1449fdde-4ae2-4911-a6b5-26a0805e44d4
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_items}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  3456206b-0211-42fd-a68a-b07cef972f0c:
    contentColumnType: text
    fieldGroup: null
    handle: headlineBottom
    instructions: ''
    name: 'Headline Bottom'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  36709743-a130-4430-8afa-667b7ff9ddfe:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  5b3d9079-ccd1-4561-bd6b-26ec0fafdb66:
    contentColumnType: text
    fieldGroup: null
    handle: headlineTop
    instructions: ''
    name: 'Headline Top'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  8ccb8a7f-e524-4fa5-a22f-bf9728352fd3:
    contentColumnType: text
    fieldGroup: null
    handle: topTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  b9bccb2a-535c-4a57-b71e-e7a40f23c6d6:
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames: '*'
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: typedlinkfield\fields\LinkField
handle: approach
name: Approach
sortOrder: 1
