field: 75fae3a2-537e-444b-9ee9-09a7a8dd6cb6
fieldLayouts:
  0bfca79a-9bd0-4e7c-9f26-cab534a904d8:
    tabs:
      -
        fields:
          40a80ca8-770e-41ec-90c5-3a377069f397:
            required: false
            sortOrder: 5
          ac02f53c-7746-4268-980c-3865a97e2b78:
            required: false
            sortOrder: 4
          d2e4b5f0-f68d-4801-af61-104ceac70332:
            required: false
            sortOrder: 2
          dc3dd139-9c24-41f1-9a0d-6bca18821cec:
            required: false
            sortOrder: 1
          e596ba36-6103-46d0-9160-c775680d80e3:
            required: false
            sortOrder: 3
          ef2705cc-f972-465c-a5e5-f395c14e3d55:
            required: false
            sortOrder: 7
          f9859374-ed14-4e81-81d5-647f74b8a5a7:
            required: false
            sortOrder: 6
        name: Content
        sortOrder: 1
fields:
  40a80ca8-770e-41ec-90c5-3a377069f397:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  ac02f53c-7746-4268-980c-3865a97e2b78:
    contentColumnType: text
    fieldGroup: null
    handle: headlineBottom
    instructions: ''
    name: 'Headline Bottom'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d2e4b5f0-f68d-4801-af61-104ceac70332:
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: ''
    name: Style
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Standard
            -
              - value
              - standard
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  dc3dd139-9c24-41f1-9a0d-6bca18821cec:
    contentColumnType: text
    fieldGroup: null
    handle: topTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e596ba36-6103-46d0-9160-c775680d80e3:
    contentColumnType: text
    fieldGroup: null
    handle: headlineTop
    instructions: ''
    name: 'Headline Top'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ef2705cc-f972-465c-a5e5-f395c14e3d55:
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames: '*'
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: typedlinkfield\fields\LinkField
  f9859374-ed14-4e81-81d5-647f74b8a5a7:
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: ''
    name: Items
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - fd3e4760-c8b9-447b-b685-98191b537169
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2a1a80b8-7112-4b8a-8a4a-8f9159eb6615
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 304dc5de-3f9a-46a6-b01c-99cf8fd587c3
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_items}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: boxes
name: Boxes
sortOrder: 4
