field: 75fae3a2-537e-444b-9ee9-09a7a8dd6cb6
fieldLayouts:
  d017d08c-cce3-4d73-aae4-ac75211017ed:
    tabs:
      -
        fields:
          31fcca23-3e57-4a46-b7f9-cba65d64ef43:
            required: false
            sortOrder: 1
          ceacd467-1ff5-439e-a30f-288f9a11c10b:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  31fcca23-3e57-4a46-b7f9-cba65d64ef43:
    contentColumnType: text
    fieldGroup: null
    handle: topTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ceacd467-1ff5-439e-a30f-288f9a11c10b:
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: ''
    name: Items
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - a021ec94-8abe-4cf7-9519-92947489513d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3a7a3b1e-e1a8-4920-b3f9-bff3688d8285
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a8d0b88f-df1c-42ef-b901-181f6c609e4e
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5343f982-911e-46dc-9bd6-535038a7a5bf
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_7_items}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: carousel
name: Carousel
sortOrder: 3
