field: 75fae3a2-537e-444b-9ee9-09a7a8dd6cb6
fieldLayouts:
  6a49e20a-9581-45a9-ad2a-7b3c8e0449ee:
    tabs:
      -
        fields:
          6a42c100-1e48-489b-bd13-1853f677ed75:
            required: false
            sortOrder: 3
          772e148e-2941-4300-a6b5-08af41f3f080:
            required: false
            sortOrder: 4
          a3a52c7d-4f82-45d9-8f52-c4e21fc450cc:
            required: false
            sortOrder: 5
          a4c4b808-f548-424c-8aec-7d315d1f27ea:
            required: false
            sortOrder: 2
          a8accf52-9d8a-4454-8ef0-e218b038790f:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  6a42c100-1e48-489b-bd13-1853f677ed75:
    contentColumnType: string
    fieldGroup: null
    handle: textRows
    instructions: ''
    name: 'Text Rows'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - fb89e76b-e232-49c8-a922-6cb7ee664066
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6928ec02-3b7a-4de1-adde-0228beba5ec6
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_textrows}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  772e148e-2941-4300-a6b5-08af41f3f080:
    contentColumnType: text
    fieldGroup: null
    handle: faqHeadline
    instructions: ''
    name: 'FAQ Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  a3a52c7d-4f82-45d9-8f52-c4e21fc450cc:
    contentColumnType: string
    fieldGroup: null
    handle: faq
    instructions: ''
    name: FAQ
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - ca6aeed5-7631-4a8e-9cb0-aa8cd022a261
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6eea2b32-d5ab-49af-b526-b008665b61f9
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_faq}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a4c4b808-f548-424c-8aec-7d315d1f27ea:
    contentColumnType: text
    fieldGroup: null
    handle: headlineBottom
    instructions: ''
    name: 'Headline Bottom'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  a8accf52-9d8a-4454-8ef0-e218b038790f:
    contentColumnType: text
    fieldGroup: null
    handle: headlineTop
    instructions: ''
    name: 'Headline Top'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: faqText
name: 'FAQ Text'
sortOrder: 7
