field: 75fae3a2-537e-444b-9ee9-09a7a8dd6cb6
fieldLayouts:
  2772be30-fc5d-4580-aaf1-21a1e74af000:
    tabs:
      -
        fields:
          3c6d2ed7-448f-4283-a125-a3b2c50cbc83:
            required: false
            sortOrder: 2
          3c83e925-c0be-4aeb-b38c-dd83239f07f1:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  3c6d2ed7-448f-4283-a125-a3b2c50cbc83:
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: ''
    name: Items
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 6328a935-566b-4688-896e-1b68ac0381dc
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1236f3dd-d523-4dc2-ad17-e91f54e62e13
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_6_items}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  3c83e925-c0be-4aeb-b38c-dd83239f07f1:
    contentColumnType: text
    fieldGroup: null
    handle: topTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: logoRow
name: 'Logo Row'
sortOrder: 2
