field: 1bed2d77-ef7e-4669-9d78-1cc3a14d89a1
fieldLayouts:
  2bd93b3b-c6fa-4271-8c88-d6e932100271:
    tabs:
      -
        fields:
          11cb193b-2895-402d-bf57-19544fef86fa:
            required: false
            sortOrder: 3
          31606746-c2e6-402c-9820-e548f133ccc8:
            required: false
            sortOrder: 1
          4e4a1e69-c294-4a7d-b8ba-38397bbd26d6:
            required: false
            sortOrder: 2
          635aa3a3-abab-4b6e-a1f8-49f86d5d47a4:
            required: false
            sortOrder: 5
          9f47dde6-748a-4b6b-bcbf-7264f728ebc1:
            required: false
            sortOrder: 4
          e6c7ed49-70f2-4bf8-b65c-a7a1c2e4acdb:
            required: false
            sortOrder: 6
        name: Content
        sortOrder: 1
fields:
  11cb193b-2895-402d-bf57-19544fef86fa:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  31606746-c2e6-402c-9820-e548f133ccc8:
    contentColumnType: text
    fieldGroup: null
    handle: topTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  4e4a1e69-c294-4a7d-b8ba-38397bbd26d6:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  635aa3a3-abab-4b6e-a1f8-49f86d5d47a4:
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames: '*'
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  9f47dde6-748a-4b6b-bcbf-7264f728ebc1:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  e6c7ed49-70f2-4bf8-b65c-a7a1c2e4acdb:
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: ''
    name: Items
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 64fe529b-e479-4be4-9109-b6c2eec83b4b
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a4cbf5eb-3978-4252-bf25-b9021bad3315
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 9ab60741-11b5-47e4-ad6c-27b4f6ef535c
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_items}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: services
name: Services
sortOrder: 2
