field: 226c07f0-7ca9-479c-b16f-6d5fbea235b8
fieldLayouts:
  e3dcd410-e555-4a3e-bb20-f8dce208d908:
    tabs:
      -
        fields:
          b90cd9fb-fc1e-44b0-873a-cebb65230142:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  b90cd9fb-fc1e-44b0-873a-cebb65230142:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
