field: 6a42c100-1e48-489b-bd13-1853f677ed75
fieldLayouts:
  ea175520-debb-4a9d-ab6d-5c400180ab54:
    tabs:
      -
        fields:
          6928ec02-3b7a-4de1-adde-0228beba5ec6:
            required: false
            sortOrder: 2
          fb89e76b-e232-49c8-a922-6cb7ee664066:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  6928ec02-3b7a-4de1-adde-0228beba5ec6:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  fb89e76b-e232-49c8-a922-6cb7ee664066:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
