field: ddcfcb7c-6a65-4cd9-b162-9f22cb4ed2dd
fieldLayouts:
  17f1a34a-8619-461e-9b51-cd748543d530:
    tabs:
      -
        fields:
          0cff0c74-1980-4e7e-b3c6-9e4bfc879d12:
            required: false
            sortOrder: 1
          15b8ba8b-54f8-4363-bc6b-27f6b60aea86:
            required: false
            sortOrder: 4
          3cfb52a7-63bb-4666-8f85-191ec5e579dc:
            required: false
            sortOrder: 2
          a6fe0c9e-29b9-454e-b67c-23aa50f119b0:
            required: false
            sortOrder: 5
          d83e69f3-afc6-4209-b523-6bff04a54fa6:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  0cff0c74-1980-4e7e-b3c6-9e4bfc879d12:
    contentColumnType: text
    fieldGroup: null
    handle: tabTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  15b8ba8b-54f8-4363-bc6b-27f6b60aea86:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  3cfb52a7-63bb-4666-8f85-191ec5e579dc:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a6fe0c9e-29b9-454e-b67c-23aa50f119b0:
    contentColumnType: text
    fieldGroup: null
    handle: list
    instructions: ''
    name: List
    searchable: true
    settings:
      addRowLabel: 'Zeile hinzufügen'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Text
                -
                  - handle
                  - text
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  d83e69f3-afc6-4209-b523-6bff04a54fa6:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
