field: e6c7ed49-70f2-4bf8-b65c-a7a1c2e4acdb
fieldLayouts:
  f89f0bcb-0140-4bb5-89a2-7e04d67da955:
    tabs:
      -
        fields:
          64fe529b-e479-4be4-9109-b6c2eec83b4b:
            required: false
            sortOrder: 1
          9ab60741-11b5-47e4-ad6c-27b4f6ef535c:
            required: false
            sortOrder: 3
          a4cbf5eb-3978-4252-bf25-b9021bad3315:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  64fe529b-e479-4be4-9109-b6c2eec83b4b:
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9ab60741-11b5-47e4-ad6c-27b4f6ef535c:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  a4cbf5eb-3978-4252-bf25-b9021bad3315:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
