field: 44e027fa-31e9-4ca0-b9b5-fd3a35b1861d
fieldLayouts:
  ed89f107-ad93-4d64-b4df-0e60f1724346:
    tabs:
      -
        fields:
          269db735-f150-4c88-889c-580dd798b7fa:
            required: false
            sortOrder: 2
          2a0496c3-d3f9-41df-b87c-8b17efc4cee5:
            required: false
            sortOrder: 3
          c7eec9ee-a40e-4a14-8598-85600ed9af52:
            required: false
            sortOrder: 1
          d5397d86-ea61-4dd3-910b-3f8032b318fd:
            required: false
            sortOrder: 6
          e36985b5-1447-477b-bd4e-af862448bd9b:
            required: false
            sortOrder: 5
          f1d04a08-d5e4-467d-8750-4458abfceba1:
            required: false
            sortOrder: 4
          fcb3cf30-c4af-488d-bb95-7e52c4880f65:
            required: false
            sortOrder: 7
        name: Content
        sortOrder: 1
fields:
  269db735-f150-4c88-889c-580dd798b7fa:
    contentColumnType: text
    fieldGroup: null
    handle: headlineBottom
    instructions: ''
    name: 'Headline Bottom'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  2a0496c3-d3f9-41df-b87c-8b17efc4cee5:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  c7eec9ee-a40e-4a14-8598-85600ed9af52:
    contentColumnType: text
    fieldGroup: null
    handle: headlineTop
    instructions: ''
    name: 'Headline Top'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d5397d86-ea61-4dd3-910b-3f8032b318fd:
    contentColumnType: text
    fieldGroup: null
    handle: teaserText
    instructions: ''
    name: 'Teaser Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  e36985b5-1447-477b-bd4e-af862448bd9b:
    contentColumnType: text
    fieldGroup: null
    handle: teaserHeadline
    instructions: ''
    name: 'Teaser Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  f1d04a08-d5e4-467d-8750-4458abfceba1:
    contentColumnType: string
    fieldGroup: null
    handle: teaserImage
    instructions: ''
    name: 'Teaser Image'
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fcb3cf30-c4af-488d-bb95-7e52c4880f65:
    contentColumnType: text
    fieldGroup: null
    handle: teaserButton
    instructions: ''
    name: 'Teaser Button'
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames: '*'
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: typedlinkfield\fields\LinkField
