field: d02fada0-1ec0-4584-ba0b-dcff0e38ad31
fieldLayouts:
  91c9ce93-7067-432e-b4df-621c818f3593:
    tabs:
      -
        fields:
          33f8b7ea-9101-47b0-9208-1863bd70bb60:
            required: false
            sortOrder: 3
          8270693a-124e-4a07-bc99-8230bfb62901:
            required: false
            sortOrder: 1
          a66e80ff-edd5-4853-a5d1-9d9d62e298e5:
            required: false
            sortOrder: 2
          bd229fd6-9dd6-4f5c-af59-2bf483f0c153:
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
fields:
  33f8b7ea-9101-47b0-9208-1863bd70bb60:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  8270693a-124e-4a07-bc99-8230bfb62901:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a66e80ff-edd5-4853-a5d1-9d9d62e298e5:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  bd229fd6-9dd6-4f5c-af59-2bf483f0c153:
    contentColumnType: text
    fieldGroup: null
    handle: contentText
    instructions: ''
    name: Content
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
