field: ceacd467-1ff5-439e-a30f-288f9a11c10b
fieldLayouts:
  f916c6fc-0573-448a-ba86-260fc6b763f8:
    tabs:
      -
        fields:
          3a7a3b1e-e1a8-4920-b3f9-bff3688d8285:
            required: false
            sortOrder: 2
          5343f982-911e-46dc-9bd6-535038a7a5bf:
            required: false
            sortOrder: 4
          a021ec94-8abe-4cf7-9519-92947489513d:
            required: false
            sortOrder: 1
          a8d0b88f-df1c-42ef-b901-181f6c609e4e:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  3a7a3b1e-e1a8-4920-b3f9-bff3688d8285:
    contentColumnType: text
    fieldGroup: null
    handle: subline
    instructions: ''
    name: Subline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  5343f982-911e-46dc-9bd6-535038a7a5bf:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  a021ec94-8abe-4cf7-9519-92947489513d:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a8d0b88f-df1c-42ef-b901-181f6c609e4e:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
