field: aab9bb2e-92bd-42e8-81d2-b1cf1d34790d
fieldLayouts:
  5c937e9f-6132-408c-bb00-2d531a1b5e4a:
    tabs:
      -
        fields:
          35bc5f82-8318-47f2-931a-29e57e566ffe:
            required: false
            sortOrder: 4
          8f8844b9-d54e-472e-bb3b-b63e3697e7ac:
            required: false
            sortOrder: 3
          bb4fc9aa-5ccc-46d9-a881-259f87c2fa04:
            required: false
            sortOrder: 2
          fd32bd9f-5530-4a97-b588-0fee299d2df7:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  35bc5f82-8318-47f2-931a-29e57e566ffe:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  8f8844b9-d54e-472e-bb3b-b63e3697e7ac:
    contentColumnType: text
    fieldGroup: null
    handle: headlineBottom
    instructions: ''
    name: 'Headline Bottom'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  bb4fc9aa-5ccc-46d9-a881-259f87c2fa04:
    contentColumnType: text
    fieldGroup: null
    handle: headlineTop
    instructions: ''
    name: 'Headline Top'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  fd32bd9f-5530-4a97-b588-0fee299d2df7:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds: null
      defaultUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:89e317dc-643d-49e4-a730-f8ce114a6644'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
